### PR TITLE
MAGE-943: polyfill.io removed from CSP whitelist

### PR DESCRIPTION
**Pull request by mrahman3177**
**Summary**
polyfill.io removed from CSP whitelist

### CODE REVIEW

**Comment by damcou** [comment]
Does this PR targets the master branch on purpose ?

**Review by cammonro — CHANGES_REQUESTED** [review]
Looks good to me. However, please rebase this PR against `release/3.13.5` and provide a PR for `release/3.14.0-beta`

**Comment by mrahman3177** [comment]
@damcou , yes, it's part of our branching strategy. For patch release we branch off of master and create PR against master.

**Comment by cammonro** [comment]
> @damcou , yes, it's part of our branching strategy. For patch release we branch off of master and create PR against master.

Partly right. We want to branch our current release patches from `master` but PR's should be merge to the target release branch.

**Pull request closed without merging**
