### PR TITLE
[magento2.4-requirements]:

### PR DESCRIPTION
**Pull request by jeroenschipper-guapa**
- Added correct magento framework requirement for magento2.4

**Summary**
This PR adds the possibility to install the module with composer for Magento 2.4

### CODE REVIEW

**Comment by pchoate-blueacorn** [comment]
@damcou any idea on the timeline to get this merged in? I have a client with a Magento 2.4 upgrade in progress but we're block by this module not supporting 2.4.

**Comment by palviggi-flagbit** [comment]
is that enough? isn't there any deprecated classes that should be replaced? (especially with the new ES requirement). 
what about php 7.4? we also need to install a new 2.4 instance and would like to not having to update the system by next year but use the latest php

**Comment by jasuten** [comment]
You will get an error when trying to compile the site with the extension, so there are more changes required to get Algolia working with 2.4. e.g
`Class Magento\Framework\Search\Adapter\Mysql\Mapper does not exist`

**Comment by damcou** [comment]
Hello @jeroenschipper-guapa @pchoate-blueacorn @palviggi-flagbit @jasuten 

Just to let you know that the 2.4 compatibility subject has been discussed and will be implemented in our next major release. The ETA for this release is end of September.

Best.

**Pull request closed without merging**
