### PR TITLE
Hide out of stock for configurable products

### PR DESCRIPTION
**Pull request by unicoder88**
Good day,

In situation when configurable product is set "In stock" but all its simple variations have qty 0, this product in fact shows as not available on frontend and shouldn't go to Algolia. I changed the check to isSaleable.

Please review :)

### CODE REVIEW

**Comment by JanPetr** [comment]
Thanks for your contribution @unicoder88! I'll review, give it few tests and come back to you. Thanks again 💯

**Comment by unicoder88** [comment]
Hi @JanPetr ,

On the second though, it might be needed to keep both checks, like in this example:

```
\Magento\ConfigurableProduct\Model\Product\Type\Configurable::getSalableUsedProducts:
...
return (int)$stockStatus->getStockStatus() === Status::STATUS_IN_STOCK && $product->isSalable();
```

**Comment by JanPetr** [comment]
Hello @unicoder88,
yes, true. Can you update the PR? Thank you!

**Comment by unicoder88** [comment]
Updated :)

**Comment by JanPetr** [comment]
Great job @unicoder88! Thank you!

**Pull request merged**
