### PR TITLE
Remove usage of around methods in ProductObserver

### PR DESCRIPTION
**Pull request by JanPetr**

### CODE REVIEW

**Comment by peterjaap** [comment]
Hi @JanPetr,

Why did you add ` || $this->configHelper->isQueueActive()` to these if statements;

https://github.com/algolia/algoliasearch-magento-2/commit/ad73c5a2641127c46fb5138318a18ca281a5c32c#diff-11e3e77a3f52e7cb0ab67db912a9d460R42

https://github.com/algolia/algoliasearch-magento-2/commit/ad73c5a2641127c46fb5138318a18ca281a5c32c#diff-11e3e77a3f52e7cb0ab67db912a9d460R63

When the indexer is scheduled, the queue willed be filled through the indexer. What this now does is that when you save a product, a rebuildStoreProductIndex queue item is *immediately* added to the queue, and then the indexer later **also** adds a queue item for the same product with the same method. This causes products to be indexed twice within a minute.

**Comment by bsuravech** [comment]
Hi @peterjaap! 

It was originally added there to compensate for missing logic in mview subscriptions. Category updates have to be updated in their products as we use category names for category filtering. 

We have a new PR that updates the plugins added in this PR that removes the isQueueActivate() check. Can you please review these changes to see if this helps you out: 

https://github.com/algolia/algoliasearch-magento-2/pull/819

We're looking to add this update to the next release awaiting on some testing fixes. Let us know what you think and if you have any further feedback, please let us know in PR#819. Thanks!

**Comment by peterjaap** [comment]
@bsuravech those are changes in the CategoryObserver, I'm running into this issue with the ProductObserver

**Comment by bsuravech** [comment]
Hey @peterjaap, AH okay. Sorry about that. I think they were added in the same vain. We'll create a ticket and a subsequent PR for that. Thanks for bringing this to our attention!

**Pull request merged**
