### PR TITLE
convert html content to UTF-8 before trim tags

### PR DESCRIPTION
**Pull request by vmalyk**
Pull request for issue #220

### CODE REVIEW

**Comment by JanPetr** [comment]
Thanks @vmalyk!
Would it be possible for you to add a test for that?

**Comment by vmalyk** [comment]
Hi, I think  It would be difficult and what cases need tot update in current version integration test

**Comment by JanPetr** [comment]
Hello @vmalyk, I tested your PR, but still found some edge cases.
I created a PR #227 including test. Could you pls give it a try if it works properly on your side?

**Comment by vmalyk** [comment]
Hello @JanPetr , I tested latest changes and looks good on our data.
Thanks for help.

**Comment by JanPetr** [comment]
Thanks for getting back to me @vmalyk 👍 
So I'm closing this PR and merging the new one. Cheers!

**Pull request closed without merging**
