### PR TITLE
Fix Add to cart button

### PR DESCRIPTION
**Pull request by JanPetr**

### CODE REVIEW

**Comment by JanPetr** [comment]
Fixes #98

**Comment by maxiloc** [comment]
👍  Insane

**Comment by richdynamix** [comment]
👍 Awesome work @JanPetr Any idea when we could expect it released?

**Comment by JanPetr** [comment]
Today it's gonna be merged in master branch and if everything goes well, I will tag it with release version on the beginning of next week.
But feel free to update from `dev-master` later today (I will ping you) and give it a try, I'd really appreciate feedback.

**Pull request merged**
