### PR TITLE
Fixing order of setting parameters

### PR DESCRIPTION
**Pull request by JosephMaxwell**
**Summary**
When working with a multi-store-view application, I found that the default request path (from the `url_rewrite`) table was selected. This caused the `request_path` from the default store to be loaded instead of the one associated with the current store.

image

*Before:*
image

**Result**
image

### CODE REVIEW

**Comment by JosephMaxwell** [comment]
I'm not sure why the `phpcompatibility` check failed. It should have worked fine.

**Comment by 0livier** [comment]
Hey @JosephMaxwell. 

Many thanks for your PR :tada: 

There's something fishy in the phpcompatibility test. I'll fix that.

**Comment by JosephMaxwell** [comment]
@0livier and @bsuravech do we know when this will get merged? Otherwise, I'll create a hotfix for this, but no need to spend the time if this will be done soon.

**Comment by damcou** [comment]
Hello @JosephMaxwell ,

This PR is part of a group of PRs that are being reviewed and hopefully added to our next released coming in the coming days / week. 

Sorry for the delay, we will update everything very soon.

**Pull request merged**
