### PR TITLE
Port the fix for images when using pub as the docroot

### PR DESCRIPTION
**Pull request by toddhainsworth**
Ref: https://github.com/aligent/algoliasearch-magento-2/commit/cd45a5261a6b763b7e269508569c36e8ca32ed4a

### CODE REVIEW

**Comment by JanPetr** [comment]
Hello @toddhainsworth,

thanks for the PRs! 💯 Can I ask you to elaborate more on why the `pub` folder needs configuration and it needs to be "fixed"? And why did you close those PRs?

Thanks a lot for you time and your contribution.

**Comment by toddhainsworth** [comment]
Hi Jan! More than happy to contribute to this repo! I closed them because I accidentally created the PR here rather than on our fork (testing it before we send it upstream :smile:  ) which we're using for projects internally.

We found that when the `pub/` folder is used as the Apache 'docroot' images for products in particular are being indexed as `<base_url>/pub/media/...` which means that when those images are fetched via Magento they 404 :-1:

This fix adds a config value to the credentials dropdown to toggle the removal of the `pub/` text during the indexing process. While I'm not 100% on the method name `fixPubUrl` (which will be changed when we send this upstream :+1: ) the behavior is simple and has proven rather consistent in our small number of tests so far!

I'm happy to create a new PR when we've fully tested this and I am able to clean up our branch so that you don't get our upstream pulls too :smile:

**Comment by JanPetr** [comment]
Hey @toddhainsworth,

definitely makes sense! I'll be happy to see your PR from a "clean" branch 💯 
Just one thing what I can see in this PR - could you move the configuration to "Advanced" section? I guess it's more suited location for such a configuration.

Thanks!

**Comment by toddhainsworth** [comment]
Hi @JanPetr 

Sounds good to me 😄 I'll fork this repo tomorrow when I get into the office and make the change from my fork (rather than our Aligent one because that's got a bunch of work that we're not ready to push upstream yet). I'll then raise a PR and tag you in it! 😄 

Cheers!

**Comment by JanPetr** [comment]
Awesome! Thanks!

**Pull request closed without merging**
