### PR TITLE
Algolia Search Composer update for magento 2.4.4 dependencies

### PR DESCRIPTION
**Pull request by mohitalgolia**
MAGE-176, Algolia Search Composer update for Magento 2.4.4 dependencies

**Result**
Fixed guzzlehttp/guzzle conflict in Magento 2.4.4 and

### CODE REVIEW

**Comment by zeeshan2523806** [comment]
Team, can we create patch for this ? this is critical for merchants who are going through with the 2.4.4 deployment.

**Comment by mohitalgolia** [comment]
Hi @zeeshan2523806 , We are going to release a version for Magento2.4.4. Thanks

**Comment by zeeshan2523806** [comment]
Thanks @mohitalgolia , any estimation on when we would be able to release it ?

**Comment by zeeshan2523806** [comment]
@mohitalgolia any update on when can we possibly release it ?

**Comment by mohitalgolia** [comment]
> @mohitalgolia any update on when can we possibly release it ?

@zeeshan2523806 We are working on the release process. Hopefully, will release it this week. Thanks

**Comment by webamondo** [comment]
@mohitalgolia is the plan still to release this week?

**Pull request merged**
