### PR TITLE
Fix Mage-374 autocomplete issue

### PR DESCRIPTION
**Pull request by ratikant-singh**
**Summary**

**Result**

### CODE REVIEW

**Review by rachel-trott — APPROVED** [review]

**Comment by janmartendeboer** [comment]
This affects our clients as well. When can this be released?

**Comment by rachel-trott** [comment]
@janmartendeboer Thank you for reaching out. We are looking to release this fix the week of Sep 19th. In the meantime you can use this solution as a patch. Hope that helps!

**Comment by mattyl** [comment]
if you are intested the inline-block also causes problems for us

Screenshot 2022-09-21 at 12 15 26
Screenshot 2022-09-21 at 12 15 12

**Comment by deemantha22** [comment]
Hi,
Is this fix related '**_Uncaught TypeError: e.highlightedValue.split is not a function_**' error?

**Comment by rachel-trott** [comment]
Yes @deemantha22

**Comment by deemantha22** [comment]
@rachel-trott 
Thanks, I tested the patch(common.js) with default magento with sample data but still getting the error. Am I missing anything?
printscreen attached

Screenshot 2022-10-05 at 15 26 42
Screenshot 2022-10-05 at 15 26 16

**Comment by peterjaap** [comment]
@rachel-trott we also tried the patch but doesn't work for us either;

image

**Comment by deemantha22** [comment]
@rachel-trott 

After debugging many hours I found that the issue is due to data which submit into algolia. This issues happens all the aloglia module versions from 3.7.0. I am on 3.9.1 at the moment.

It shows _**Uncaught TypeError: e.highlightedValue.split**_ issue on search dropdown for below. So I have edited JSON object to be  "categories_without_path": [], and it fixed the issue. Added patch for our project. Is this a known issue?

```
"categories_without_path": [
    "Golf",
    "Golf Mats",
    "Driving Range Mats",
    "Golf Practice Mats",
    "Training Equipment",
    "Winter Golf Mats",
    "Garden Equipment"
  ],
```

```
diff --git a/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php b/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php
index 276cd7a9..c9988cf4 100755
--- a/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php
+++ b/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php
@@ -796,7 +796,7 @@ class ProductHelper
         $hierarchicalCategories = $this->getHierarchicalCategories($categoriesWithPath);

         $customData['categories'] = $hierarchicalCategories;
-        $customData['categories_without_path'] = $categories;
+        $customData['categories_without_path'] = '';
         $customData['categoryIds'] = array_values(array_unique($categoryIds));

         return $customData;
```

**Comment by peterjaap** [comment]
@rachel-trott unfortunately this issue still persists in 3.9.1

**Pull request merged**
