### PR TITLE
PHP8.2 compatibility

### PR DESCRIPTION
**Pull request by thomas-kl1**
**Summary**

Fix following error on PHP8.2

```
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Algolia\AlgoliaSearch\ViewModel\Recommend\Cart::$storeManager is deprecated in /var/www/project/magento/vendor/algolia/algoliasearch-magento-2/ViewModel/Recommend/Cart.php on line 42
```

**Result**

Add the storeManager property

### CODE REVIEW

**Comment by thomas-kl1** [comment]
Hello @mohitalgolia @tarun-algolia @rachel-trott 

Could you review this quickly? It's a major issue, the cart could not load and crash with PHP8.2.

**Comment by mohitalgolia** [comment]
Thank you for the patch, @thomas-kl1. We've successfully reproduced the issue, and it will be incorporated into our upcoming release.

**Comment by thomas-kl1** [comment]
Hello @mohitalgolia , any ETA on the next release date?

**Comment by rachel-trott** [comment]
@thomas-kl1 We are working on the next release and tentatively release will be end of February. Please use this as patch for now. Thank you for bringing this up.

**Comment by samsteele** [comment]
Please prioritise this it's a critical issue on the current Magento version, fixing this shouldn't take a month

**Comment by mohitalgolia** [comment]
We have included this issue in our 3.13.1 release and uploaded to marketplace.

**Comment by thomas-kl1** [comment]
@mohitalgolia quick question, why you copy-paste then close instead of just mergin this PR?

**Pull request closed without merging**
