### PR TITLE
Adminhtml improvements: XSS prevention, translations, etc

### PR DESCRIPTION
**Pull request by vmalyk**
**Summary**
Fixed and improved a lot of thing in adminhtml templates:

1. Added XSS prevention (escapeHtml, escapeJs, etc) in templates
2. Added as it`s possible translations
3. Change $this usage to $block (Magento guidelines)
4. Moved inline styles to web/css/common.css

Please review,
Thnx!

### CODE REVIEW

**Comment by bsuravech** [comment]
Hi @vmalyk! Thanks for the PR. Our CS rules don't allow short echo tags which is why our quality tools test are failing. We will be updating our Contribution documentation soon but since you are an active contributor in our repo, I would recommend installing our quality tools to help you lint and test before submitting a PR to avoid test failing! You can check out the repo for it here:

https://github.com/algolia/magento2-tools

**Comment by vmalyk** [comment]
Hi @bsuravech,

Thank you for your review. I`ve found solution how to check and fix code stylin. I`ve reverted shortcut usage changes and some syntax issues, but another things are relevant.
By the way, might be It`s good idea to allow short echo tags, because Magento recommend to use it and your module works on PHP 7.0 or higher (but It`ll be no in that PR scope).

Thnx!

**Comment by damcou** [comment]
Hi @vmalyk and thanks again for your work.
I only have a small issue with the template view/adminhtml/templates/common.phtml which has changed a lot in the develop branch with the admin notices refactoring : https://github.com/algolia/algoliasearch-magento-2/pull/921/files

I understand that for now it can be important for you that the develop-1.x stays up-to-date and for now I was able to merge your changes from develop-1.x to develop branch (which is our main working branch that will soon introduce the v2.0.0 of our extension). 

For this particular case, I'm not sure if we should
- First add the admin refactoring to the develop-1.x (it was not the plan to be honest ;) ) 
- Or to simply remove the changes of the common.phtml to be able to merge develop-1.x to develop again.

**Comment by vmalyk** [comment]
Hi @damcou and thank for your comments and concerns.
your small issue is related with changes from PR #921 - I reviewed that and I didn't change common.phtml file in that scope, because I think notice refactoring - it's important fix for resolving conflicts between AlgoliaSearch  and another modules (ex. issue #919). I've checked and these changes are moved without conflicts to develop-1.x and this scope.
But I see another problem - Branch develop-1.x lost sense after commit b7e7cb4768c3675c84a7952952e6b7804b2f6e99 (look as We lost some plan) - The main changes of  2.0.0(Migration to new ISv3 was merged) and  It should be fixed.
I suggest to revert develop-1.x to state before, re-push my PRs and might be move your changes from develop (Fixes for #930, 928, 929, 931, 921, 915).
The reason - it makes soft upgrade and Community`ll update to 1.x version with fixes and migrate theirs code asap to new 2.0.0 (ISv3/ISv4 and PHP API v2.0 - if it`ll be included)

Please review,
Thank you

**Comment by damcou** [comment]
@vmalyk . You're totally right, there was a unwanted merge yesterday from develop to develop1-x . 
I'll try to fix ASAP and keep you updated.
Sorry for that :( .

**Comment by damcou** [comment]
@vmalyk . So with the awesome help from @tkrugg , we managed to remove everything which was related to ISv3 from the develop-1.x branch.
Could you please check if everything seems good to you now and update the PR if needed ?
Thanks again for all of this !

**Comment by vmalyk** [comment]
Thank you @tkrugg  and @damcou for update!
I`ve re-apply changes form PR to new develop-1.x branch, checked and fixed my changes(where it was possible). In addition, I`ve fixed some points from previous PRs (literal names for "Run" models).

Please review.

**Pull request merged**
